export const tagsArr = [
  'Airport shuttle',
  'Spa and wellness centre',
  'Fitness centre',
  'Room service',
  'Parking',
  'Free WiFi',
  'Beachfront',
  'Facilities for disabled guests',
  'Family rooms',
  'Good breakfast',
  'Restaurant',
  'Pets allowed',
  '24-hour front desk',
  'Non-smoking rooms',
  'Electric vehicle charging station',
  'Swimming Pool',
  '2 swimming pools',
  'Air conditioning',
  'BBQ facilities',
  'Terrace',
  'Heating',
  'Garden',
  'Lift',
  'Laundry',
];
