export const roomTypes = ['Single room', 'Double room'];
export const tagsArr = [
  'Free toiletries',
  'Shower',
  'Bathrobe',
  'Kitchen',
  'Safety deposit box',
  'Washing machine',
  'Streaming service',
  'Toilet',
  'Sofa',
  'Fireplace',
  'Towels',
  'Linen',
  'Electric blankets',
  'Cleaning products',
  'Tile/marble floor',
  'Desk',
  'Private entrance',
  'TV',
  'Slippers',
  'Refrigerator',
  'Mosquito net',
  'Telephone',
  'Ironing facilities',
  'Iron',
  'Radio',
];
